_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 05cf98ad-fbee-4bae-b267-4202f8d4b7a3
name: 'Innoraft Movie Portal'
mail: movieportal@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/21
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
